name: Bug
description: Créer un bug et remplir automatiquement le project
title: "[BUG] "
labels: ["bug"]
body:
  - type: input
    id: summary
    attributes:
      label: Summary
      placeholder: Exemple - Le bouton enregistrer ne fonctionne pas
    validations:
      required: true

  - type: dropdown
    id: status
    attributes:
      label: Status
      options:
        - Todo
        - In Progress
        - Done
    validations:
      required: true

  - type: dropdown
    id: estimate
    attributes:
      label: Estimate
      options:
        - "1"
        - "2"
        - "3"
        - "5"
        - "8"
    validations:
      required: true

  - type: dropdown
    id: type
    attributes:
      label: Type
      options:
        - Bug
        - Feature
        - Task
    validations:
      required: true

  - type: checkboxes
    id: options
    attributes:
      label: Options
      options:
        - label: Assign me automatically

  - type: textarea
    id: details
    attributes:
      label: Details
      placeholder: Décris le problème
    validations:
      required: true