name: Task
description: Créer une tâche projet
title: "[TASK] "
labels: ["task"]
body:
  - type: input
    id: summary
    attributes:
      label: Summary
      placeholder: Exemple - Ajouter l'export PDF
    validations:
      required: true

  - type: checkboxes
    id: options
    attributes:
      label: Options
      options:
        - label: Assign me automatically

  - type: dropdown
    id: status
    attributes:
      label: Status
      options:
        - Todo
        - In Progress
        - In Review
        - Done
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - P0
        - P1
        - P2
        - P3
    validations:
      required: true

  - type: dropdown
    id: estimate
    attributes:
      label: Estimate
      options:
        - "1"
        - "2"
        - "3"
        - "5"
        - "8"
        - "13"
    validations:
      required: true

  - type: input
    id: sprint
    attributes:
      label: Sprint
      placeholder: Exemple - Sprint 12

  - type: input
    id: start_date
    attributes:
      label: Start date
      placeholder: YYYY-MM-DD

  - type: input
    id: target_date
    attributes:
      label: Target date
      placeholder: YYYY-MM-DD

  - type: textarea
    id: details
    attributes:
      label: Details
      placeholder: Décris la tâche
    validations:
      required: true